site_name: LiQuer Docs
nav:
- Home : 'index.md'
- "User Guide":
  - Query syntax: 'query.md'
  - General guide : 'guide.md'
- Examples : 'examples.md'

plugins:
- search
- mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
