site_name: LiQuer Docs
nav:
- Home : 'index.md'
- "User Guide":
  - Introduction : 'guide.md'
  - "Query syntax": 'query.md'
  - Store: 'store.md'
  - Recipes: 'recipes.md'
  - Commands: 'commands.md'
  - Examples : 'examples.md'
- API: 'api.md'

plugins:
- search
- mkdocstrings

markdown_extensions:
  - admonition
  - codehilite
